### ISSUE TITLE
trabajo en equipo de conversiones 

### ISSUE THREAD

**Issue by JulioCGz** [SistemasTecTlaxiaco/ejercicios-equipo-julio-cesar-gonzalez-lopez#2]
[travjo en equipo matematicas disccretas.pdf](https://github.com/SistemasTecTlaxiaco/ejercicios-equipo-julio-cesar-gonzalez-lopez/files/7150365/travjo.en.equipo.matematicas.disccretas.pdf)

**Comment by Erick-3as** [comment]
TU TRABAJO DE EQUIPO TE DOY UN 15% POR QUE TE FALTARON UNOS CONCEPTOS

**Comment by josealfredo79** [comment]
Se evaluo de acuerdo a rúbrica??Bien hecho y revisado
