### ISSUE TITLE
EJERCICIOS. MARIBEL LUCERO

### ISSUE THREAD

**Issue by lucero012** [SistemasTecTlaxiaco/ejercicios-equipo-julio-cesar-gonzalez-lopez#4]
[trabajo.en.equipo.matematicas.disccretas.pdf](https://github.com/SistemasTecTlaxiaco/ejercicios-equipo-julio-cesar-gonzalez-lopez/files/7210519/travjo.en.equipo.matematicas.disccretas.pdf)

**Comment by lourdeshernandez2003** [comment]
15% porque no cumple con todos los puntos que pide la rubrica.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
