### ISSUE TITLE
ejercicios 

### ISSUE THREAD

**Issue by yaritzaov123** [SistemasTecTlaxiaco/ejercicios-equipo-julio-cesar-gonzalez-lopez#5]
[Uploading travjo.en.equipo.matematicas.disccretas.pdf…]()

**Comment by yanet02** [comment]
En sus trabajos no tiene el objetivo, introducción, tampoco los materiales y tampoco las referencias por lo tanto mi equipo y yo te damos el 15% por sus ejercicios..

**Comment by josealfredo79** [comment]
Bien hecho y revisado
